using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MinimalisticWPF.Generator
{
    [Generator(LanguageNames.CSharp)]
    public class BackendCodeGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classDeclarations = AnalizeHelper.DefiningFilter(context);
            var compilationAndClasses = AnalizeHelper.GetValue(context, classDeclarations);
            context.RegisterSourceOutput(compilationAndClasses, GenerateSource);
        }
        private static void GenerateSource(SourceProductionContext context, (Compilation Compilation, ImmutableArray<ClassDeclarationSyntax> Classes) input)
        {
            var (compilation, classes) = input;

            Dictionary<INamedTypeSymbol, ClassDeclarationSyntax> uniqueTargets = [];  // 类唯一性
            Dictionary<INamedTypeSymbol, HashSet<string>> namespaces = [];      // 合并多分部中所有的命名空间引用
            foreach (var classDeclaration in classes)
            {
                SemanticModel model = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
                var classSymbol = model.GetDeclaredSymbol(classDeclaration);
                if (classSymbol == null)
                    continue;

                if (namespaces.TryGetValue(classSymbol, out var hashset))
                {
                    foreach (var ns in ClassRoslyn.GetReferencedNamespaces(classSymbol))
                    {
                        hashset.Add(ns);
                    }
                }
                else
                {
                    namespaces.Add(classSymbol, ClassRoslyn.GetReferencedNamespaces(classSymbol));
                }

                if (!uniqueTargets.TryGetValue(classSymbol, out _))
                {
                    uniqueTargets.Add(classSymbol, classDeclaration);
                }
            }

            Dictionary<string, StringBuilder> generatedSources = []; // 生成文本
            foreach (var kvp in uniqueTargets)
            {
                var classRoslyn = new ClassRoslyn(kvp.Value, kvp.Key, compilation);
                var fileName = AnalizeHelper.GetFileName(kvp.Key, kvp.Value);

                if (!generatedSources.TryGetValue(fileName, out var sourceBuilder))
                {// 以下按三种情况讨论项目
                    sourceBuilder = new StringBuilder();
                    sourceBuilder.AppendLine($"// <auto-generated/>");
                    if (classRoslyn.IsContextConfig && !classRoslyn.IsViewModel)
                    {// 配置ViewModel，以依赖属性的自动生成为主
                        var vm = uniqueTargets.Values.FirstOrDefault(x => x.Identifier.Text == classRoslyn.ViewModelTypeName
                                             && (string.IsNullOrEmpty(classRoslyn.ViewModelValidation) || compilation.GetSemanticModel(x.SyntaxTree)?.GetDeclaredSymbol(x)?.ContainingNamespace.ToString() == classRoslyn.ViewModelValidation));
                        if (vm != null)
                        {
                            SemanticModel vmModel = compilation.GetSemanticModel(vm.SyntaxTree);
                            var vmsymbol = vmModel.GetDeclaredSymbol(vm);
                            if (vmsymbol != null)
                            {
                                if (!string.IsNullOrEmpty(classRoslyn.ViewModelValidation) && vmsymbol.ContainingNamespace.ToString() != classRoslyn.ViewModelValidation)
                                {
                                    continue;
                                }
                                sourceBuilder.AppendLine(classRoslyn.GenerateUsing(namespaces[vmsymbol]));
                                sourceBuilder.AppendLine(classRoslyn.GenerateNamespace());
                                sourceBuilder.AppendLine(classRoslyn.GeneratePartialClass());
                                sourceBuilder.AppendLine(classRoslyn.GenerateITA());
                                var vmclassRoslyn = new ClassRoslyn(vm, vmsymbol, compilation);
                                var localName = classRoslyn.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                                var vmName = vmclassRoslyn.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                                sourceBuilder.AppendLine(classRoslyn.GenerateModelReader(vmclassRoslyn));
                                sourceBuilder.AppendLine(vmclassRoslyn.GenerateInitializeInView(vmsymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
                                sourceBuilder.AppendLine(vmclassRoslyn.GenerateDependencyProperties(localName, vmName));
                                sourceBuilder.AppendLine(vmclassRoslyn.GenerateHoverDependencyProperties(localName, vmName));
                                sourceBuilder.AppendLine(classRoslyn.GenerateEnd());
                                generatedSources[fileName] = sourceBuilder;
                            }
                        }
                    }
                    else if (classRoslyn.IsViewModel && !classRoslyn.IsContextConfig)
                    {// 定义ViewModel，一切效果直接以C#实现
                        sourceBuilder.AppendLine(classRoslyn.GenerateUsing(namespaces[kvp.Key]));
                        sourceBuilder.AppendLine(classRoslyn.GenerateNamespace());
                        sourceBuilder.AppendLine(classRoslyn.GeneratePartialClass());
                        sourceBuilder.AppendLine(classRoslyn.GenerateConstructor());
                        sourceBuilder.AppendLine(classRoslyn.GenerateIPC());
                        sourceBuilder.AppendLine(classRoslyn.GenerateITA());
                        var csFullName = classRoslyn.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        foreach (var fieldRoslyn in classRoslyn.FieldRoslyns)
                        {
                            sourceBuilder.AppendLine(fieldRoslyn.GenerateCode(csFullName));
                        }
                        sourceBuilder.AppendLine(classRoslyn.GenerateModelReader());
                        sourceBuilder.AppendLine(classRoslyn.GenerateHoverControl());
                        sourceBuilder.AppendLine(classRoslyn.GenerateEnd());
                        generatedSources[fileName] = sourceBuilder;
                    }
                    else
                    {// 不属于此项目分析的范畴
                        continue;
                    }
                }
            }

            foreach (var kvp in generatedSources)
            {
                context.AddSource(kvp.Key, SourceText.From(kvp.Value.ToString(), Encoding.UTF8));
            }  // 输出生成内容
        }
    }
}
